flags: {}

extra-package-dbs: []

allow-newer: true
resolver: lts-11.1

nix:
    packages: [gmp,git]

packages:
  - location: .

  - location:
      git: https://github.com/dhall-lang/dhall-json
      commit: d6adaa265dcf8ab5899396b05d612b2d8092dca4
    extra-dep: true
